name: Pushing to GitHub Pages

on:
 push:
  branches:
   - main

permissions:
 contents: read
 pages: write
 id-token: write

jobs:
  deploy:
   environment:
    name: github-pages
    url: ${{ steps.deployment.outputs.page_url}}
   runs-on: ubuntu-latest
   steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'
    - name: Deploy to Pages
      id: deployment
      uses: actions/deploy-pages@v4
